# ansible-playbook main.yml -i inventory -K 
# ansible-playbook main.yml -i inventory -K --tags vs-code
---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

general:
    local_home: "{{ lookup('env','HOME') }}"
    user_name: "{{ lookup('env', 'USER') }}"

configure_vs_code: true
configure_oh_my_zsh: true
configure_dock: true
dockitems_remove_all: true

dockitems_disabled:
  - all

dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/charliehwang/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .aliases
  - .zshrc
  - .gitconfig
  - .osx
  - .vimrc
  - .config/vscode
  - .config/karabiner

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  - tmux
  - git
  - github/gh/gh
  # - go
  # - gpg
  # - httpie
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  - nmap
  - node
  - nvm
  # - php
  - ssh-copy-id
  # - cowsay
  # - readline
  # - openssl
  # - pv
  - wget
  # - wrk
  - jump

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers # Logitech-options
  - homebrew/cask-fonts # Meslo LG M Regular for Powerline Font
  - neovim/neovim          # neovim


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-meslo-for-powerline # brew search --cask /meslo
  - karabiner-elements
  - microsoft-office
  - slack
  - notion
  - 1password
  - docker
  - microsoft-edge
  - firefox
  - google-chrome
  - handbrake
  - iterm2
  - iina
  - vlc
  # - logitech-options
  - encryptme
    # Quick Look plugins
  - qlcolorcode            # syntax highlighting
  - qlstephen              # files without file extensions
  - qlmarkdown             # markdown
  - quicklook-json         # json
  - quicklook-csv          # csv
  - qlimagesize            # display image size and resolution
  - webpquicklook          # webp


  # None yet

  # - dropbox
  # - chromedriver
  # - licecap
  # - sequel-ace
  # - sublime-text
  # - transmit
  # - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { name: MSRemoteDesktop, id: 715768417 }
  - { name: Screens4, id: 1224268771 }
  - { name: JumpDesktop, id: 524141863 }
  # - { name: Xcode, id: 497799835 }
mas_email: "charliehwang@mac.com"
mas_password: ""

# User configuration
users:
  - username: "{{general.user_name}}"

# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
oh_my_zsh_install: yes
oh_my_zsh_theme: agnoster
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions

visual_studio_code_extensions:
  - vscodevim.vim

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: 
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
  - name: yarn                 # package manager
  - name: jsonlint             # vim linter for json
  - name: markdownlint-cli     # vim linter for markdown
  - name: eslint               # vim linter for javascript
  - name: eslint-plugin-import # dependency of global eslint

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# tasks/iterm2.yml settings.
iterm2_enable_automatic_updates: true
iterm2_preference_folder: "{{ playbook_dir }}/../files"

# tasks/vs-code-extensions.yml
visual_studio_code_extensions:
  - vscodevim.vim

# tasks/default-applications.yml
default_applications:
  # Iina
  - { extension: avi, handler: com.colliderli.iina }
  - { extension: flv, handler: com.colliderli.iina }
  - { extension: mkv, handler: com.colliderli.iina }
  - { extension: mov, handler: com.colliderli.iina }
  - { extension: mp4, handler: com.colliderli.iina }
  - { extension: mpg, handler: com.colliderli.iina }
  # # MacDown
  # - { extension: md, handler: com.uranusjr.macdown }
  # # Chrome
  # - { extension: html, handler: com.google.Chrome, roles: '' }
  # - { extension: xml, handler: com.google.Chrome }
  # # MacVim
  # - { extension: cfg, handler: org.vim.MacVim }
  # - { extension: css, handler: org.vim.MacVim }
  # - { extension: inc, handler: org.vim.MacVim }
  # - { extension: js, handler: org.vim.MacVim }
  # - { extension: json, handler: org.vim.MacVim }
  # - { extension: php, handler: org.vim.MacVim }
  # - { extension: scss, handler: org.vim.MacVim }
  # - { extension: txt, handler: org.vim.MacVim }
  # - { extension: yml, handler: org.vim.MacVim }

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
