---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

    - role: gantsign.oh-my-zsh
      when: configure_oh_my_zsh
      users: 
        - username: "{{general.user_name}}"
      tags: ['oh-my-zsh']

    - role: gantsign.visual-studio-code
      when: configure_vs_code
      tags: ['vs-code']

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']


  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    # - import_tasks: tasks/oh-my-zsh.yml
    #   tags: ['oh-my-zsh']

    # - import_tasks: tasks/vs-code-extensions.yml
    #   tags: ['vs-code']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']