# ansible-galaxy install -r requirements.yml 
---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.visual-studio-code

collections:
  - name: geerlingguy.mac
